spring:
  application:
    name: jfcApplication
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_database
    username: root
    password: imishaan
server:
  port: 8080

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  bootstrap-servers: localhost:9092
  consumer:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group-id: jfc-group
    auto-offset-reset: earliest
  listener:
    ack-mode: record
  template:
    default-topic: job-ingestion

logging:
  level:
    org:
      apache:
        kafka: ERROR
    springframework:
      kafka: ERROR
    kafka: ERROR

jfc:
  topics:
    ingestion: job-ingestion
    status: common-job-status
    toolA: toolA-destination
    toolB: toolB-destination
    toolC: toolC-destination