spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_database?useSSL=false
    username: root
    password: imishaan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "jfc-group"
      auto-offset-reset: "earliest"
    listener:
      ack-mode: "record"
    template:
      default-topic: "job-ingestion"

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR

# Kafka topic names
jfc:
  topics:
    ingestion: "job-ingestion"
    status: "common-job-status"
    toolA: "toolA-destination"
    toolB: "toolB-destination"
    toolC: "toolC-destination"
