server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_database
    username: root
    password: imishaan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "jfc-group"
      auto-offset-reset: "earliest"
    listener:
      ack-mode: "record"
    template:
      default-topic: "job-ingestion"

# Dispatcher-related configuration
#dispatcher:
#  thread:
#    pool:
#      size: 5            # <--- Configurable thread pool size (example)
#  jobpage:
#    size: 500           # <--- Maximum number of NEW jobs fetched per page

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # CONSUMER CONFIG
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # Extra properties for JSON deserialization
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "java.util.HashMap"
    listener:
      ack-mode: record

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR

# Kafka topic names
jfc:
  topics:
    ingestion: "job-ingestion"
    status: "common-job-status"
    toolA: "toolA-destination"
    toolB: "toolB-destination"
    toolC: "toolC-destination"
  global-concurrency-limit: 8

